"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronLeft, Image as ImageIcon, Mail, Phone, Plus, Save, StickyNote, X } from "lucide-react";
import { WORKFLOW_LABELS, WORKFLOW_STATUSES, type WorkflowStatus } from "@/lib/workflow";
import type { BusinessImage, BusinessLead } from "./page";

export default function BusinessWorkspace({ lead, previousId, nextId, statusFilter }: { lead:BusinessLead; previousId:string|null; nextId:string|null; statusFilter:WorkflowStatus|"all" }) {
  const [notes,setNotes]=useState(lead.admin_notes||"");
  const [status,setStatus]=useState<WorkflowStatus>(lead.workflow_status);
  const [redesigns,setRedesigns]=useState<BusinessImage[]>(lead.redesign_images.length?lead.redesign_images:[{url:"",description:""}]);
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const query=statusFilter==="all"?"":`?status=${statusFilter}`;
  async function save(){setSaving(true);setError("");setMessage("");try{const res=await fetch(`/api/admin/leads/${lead.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({adminNotes:notes,workflowStatus:status,redesignImages:redesigns})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Changes could not be saved.");setStatus(body.workflowStatus);setMessage("Business workspace saved.")}catch(e){setError(e instanceof Error?e.message:"Changes could not be saved.")}finally{setSaving(false)}}
  return <main className="business-page">
    <header className="business-topbar"><Link href="/dashboard" className="back-link"><ChevronLeft size={17}/>Lead workspace</Link><img src="/brand/chalkframe-logo-dark.svg" alt="Chalkframe"/><nav className="record-nav"><Link aria-disabled={!previousId} className={!previousId?"disabled":""} href={previousId?`/dashboard/leads/${previousId}${query}`:"#"}><ArrowLeft size={16}/><span>Previous</span></Link><span className="technical">Business record</span><Link aria-disabled={!nextId} className={!nextId?"disabled":""} href={nextId?`/dashboard/leads/${nextId}${query}`:"#"}><span>Next</span><ArrowRight size={16}/></Link></nav></header>
    <section className="business-hero"><div><span className="technical">Lead intelligence / {new Date(lead.created_at).toLocaleDateString("en-IN",{dateStyle:"medium"})}</span><h1>{lead.title||"Meta ad business"}</h1><a href={lead.ad_url} target="_blank" rel="noreferrer">Open source ad <ArrowUpRight size={14}/></a></div><label className="status-select">Workflow status<select value={status} onChange={e=>setStatus(e.target.value as WorkflowStatus)}>{WORKFLOW_STATUSES.map(item=><option key={item} value={item}>{WORKFLOW_LABELS[item]}</option>)}</select></label></section>
    <section className="workflow-rail">{WORKFLOW_STATUSES.map((item,index)=>{const current=WORKFLOW_STATUSES.indexOf(status);return <div className={index<=current?"reached":""} key={item}><i>{index<current?<Check size={13}/>:index+1}</i><span>{WORKFLOW_LABELS[item]}</span></div>})}</section>
    <div className="business-layout"><div className="business-canvas">
      <section className="business-section"><div className="section-heading"><div><span className="technical">Original research</span><h2>Active ad creatives</h2></div><span>{lead.images.length} image{lead.images.length!==1?"s":""}</span></div>{lead.images.length?<div className="original-gallery">{lead.images.map((image,index)=><figure key={image.id||index}><div><img src={image.url} alt={image.description||`Original creative ${index+1}`}/></div><figcaption><strong>Creative {String(index+1).padStart(2,"0")}</strong><p>{image.description||"No description added."}</p><a href={image.url} target="_blank" rel="noreferrer">Open original <ArrowUpRight size={12}/></a></figcaption></figure>)}</div>:<div className="gallery-empty"><ImageIcon/><strong>No original images</strong><p>The employee completed this lead without an image reference.</p></div>}</section>
      <section className="business-section redesign-section"><div className="section-heading"><div><span className="technical">Chalkframe output</span><h2>Redesign</h2></div><button onClick={()=>setRedesigns([...redesigns,{url:"",description:""}])}><Plus size={15}/>Add redesign</button></div><p className="section-intro">Add the redesigned creative URLs here. Saving the first redesign automatically moves this business to “Redesign created”.</p><div className="redesign-editor">{redesigns.map((image,index)=><div className="redesign-card" key={index}>{image.url?<div className="redesign-preview"><img src={image.url} alt={`Redesign ${index+1}`}/></div>:<div className="redesign-placeholder"><ImageIcon size={26}/><span>Preview</span></div>}<div className="redesign-fields"><label>Image URL<input type="url" value={image.url} onChange={e=>setRedesigns(redesigns.map((item,i)=>i===index?{...item,url:e.target.value}:item))} placeholder="https://..."/></label><label>Description<input value={image.description||""} onChange={e=>setRedesigns(redesigns.map((item,i)=>i===index?{...item,description:e.target.value}:item))} placeholder="What changed in this redesign"/></label></div>{redesigns.length>1&&<button className="remove-redesign" aria-label="Remove redesign" onClick={()=>setRedesigns(redesigns.filter((_,i)=>i!==index))}><X size={14}/></button>}</div>)}</div></section>
    </div><aside className="business-sidebar">
      <section className="fact-card"><span className="technical">Business details</span><h2>Contact record</h2><Fact label="Facebook" value={lead.facebook_url} link/><Fact label="Instagram" value={lead.instagram_url} link/><Fact label="Email" value={lead.email} icon={<Mail size={14}/>} href={lead.email?`mailto:${lead.email}`:undefined}/><Fact label="Phone" value={lead.phone} icon={<Phone size={14}/>} href={lead.phone?`tel:${lead.phone}`:undefined}/><Fact label="Website" value={lead.website_status==="no"?"No website found":lead.website_url||"Not checked"} link={Boolean(lead.website_url)}/><div className="research-notes"><span>Employee notes</span><p>{lead.notes||"No additional information was added."}</p></div><div className="completed-meta"><span>Research owner</span><strong>{lead.completed_by_name||"Not completed"}</strong>{lead.completed_at&&<small>{new Date(lead.completed_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</small>}</div></section>
      <section className="admin-note-card"><div><StickyNote size={17}/><span className="technical">Private admin notes</span></div><p>Only administrators can read these notes.</p><textarea rows={8} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add follow-up context, positioning ideas, or contact outcomes…"/></section>
      {(message||error)&&<div className={`workspace-message ${error?"error":""}`}>{error||message}</div>}<button className="save-workspace" onClick={save} disabled={saving}><Save size={16}/>{saving?"Saving…":"Save workspace"}</button>
    </aside></div>
  </main>
}

function Fact({label,value,link,href,icon}:{label:string;value:string|null;link?:boolean;href?:string;icon?:React.ReactNode}){const target=href||(link&&value?value:undefined);return <div className="fact"><span>{label}</span>{target?<a href={target} target={target.startsWith("http")?"_blank":undefined} rel="noreferrer">{icon}{value}<ArrowUpRight size={11}/></a>:<strong>{value||"Not found"}</strong>}</div>}
