"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronLeft, Copy, Image as ImageIcon, Mail, Phone, Plus, Save, StickyNote, Trash2, X } from "lucide-react";
import { WORKFLOW_LABELS, WORKFLOW_STATUSES, type WorkflowStatus } from "@/lib/workflow";
import type { BusinessImage, BusinessLead } from "./page";

export default function BusinessWorkspace({ lead, previousId, nextId, statusFilter }: { lead:BusinessLead; previousId:string|null; nextId:string|null; statusFilter:WorkflowStatus|"all" }) {
  const router=useRouter();
  const [notes,setNotes]=useState(lead.admin_notes||"");
  const [chatgptUrl,setChatgptUrl]=useState(lead.chatgpt_url||"");
  const [status,setStatus]=useState<WorkflowStatus>(lead.workflow_status);
  const [redesigns,setRedesigns]=useState<BusinessImage[]>(lead.redesign_images.length?lead.redesign_images:[{url:"",description:""}]);
  const [selectedImage,setSelectedImage]=useState<BusinessImage|null>(null); const [copied,setCopied]=useState(false);
  const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [confirmDelete,setConfirmDelete]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const query=statusFilter==="all"?"":`?status=${statusFilter}`;
  useEffect(()=>{if(!selectedImage)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelectedImage(null)};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[selectedImage]);
  function showImage(image:BusinessImage){setSelectedImage(image);setCopied(false)}
  async function copyDescription(){if(!selectedImage?.description)return;await navigator.clipboard.writeText(selectedImage.description);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}
  async function persist(nextRedesigns=redesigns,success="Business workspace saved."){const res=await fetch(`/api/admin/leads/${lead.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({adminNotes:notes,chatgptUrl,workflowStatus:status,redesignImages:nextRedesigns})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Changes could not be saved.");setStatus(body.workflowStatus);setMessage(success)}
  async function save(){setSaving(true);setError("");setMessage("");try{await persist()}catch(e){setError(e instanceof Error?e.message:"Changes could not be saved.")}finally{setSaving(false)}}
  async function uploadPastedImage(file:File){setUploading(true);setError("");setMessage("Optimizing and uploading pasted image…");try{const form=new FormData();form.set("file",file);const response=await fetch("/api/admin/uploads",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"Image upload failed.");const uploaded={url:String(result.url),description:""};const next=redesigns.length===1&&!redesigns[0].url&&!redesigns[0].description?[uploaded]:[...redesigns,uploaded];setRedesigns(next);await persist(next,`Image compressed ${result.savedPercent}% and saved to this business.`)}catch(e){setMessage("");setError(e instanceof Error?e.message:"Image upload failed.")}finally{setUploading(false)}}
  function handlePaste(event:React.ClipboardEvent){const image=[...event.clipboardData.items].find(item=>item.kind==="file"&&item.type.startsWith("image/"))?.getAsFile();if(!image)return;event.preventDefault();event.stopPropagation();if(!uploading)void uploadPastedImage(image)}
  async function remove(){setSaving(true);setError("");try{const res=await fetch(`/api/admin/leads/${lead.id}`,{method:"DELETE"});const body=await res.json();if(!res.ok)throw new Error(body.error||"Could not delete this business.");router.push("/dashboard");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not delete this business.");setConfirmDelete(false);setSaving(false)}}
  return <main className="business-page">
    <header className="business-topbar"><Link href="/dashboard" className="back-link"><ChevronLeft size={17}/>Lead workspace</Link><img src="/brand/chalkframe-logo-dark.svg" alt="Chalkframe"/><nav className="record-nav"><Link aria-disabled={!previousId} className={!previousId?"disabled":""} href={previousId?`/dashboard/leads/${previousId}${query}`:"#"}><ArrowLeft size={16}/><span>Previous</span></Link><span className="technical">Business record</span><Link aria-disabled={!nextId} className={!nextId?"disabled":""} href={nextId?`/dashboard/leads/${nextId}${query}`:"#"}><span>Next</span><ArrowRight size={16}/></Link></nav></header>
    <section className="business-hero"><div><h1>{lead.title||"Meta ad business"}</h1><a href={lead.ad_url} target="_blank" rel="noreferrer">Open source ad <ArrowUpRight size={14}/></a></div><label className="status-select">Workflow status<select value={status} onChange={e=>setStatus(e.target.value as WorkflowStatus)}>{WORKFLOW_STATUSES.map(item=><option key={item} value={item}>{WORKFLOW_LABELS[item]}</option>)}</select></label></section>
    <section className="workflow-rail">{WORKFLOW_STATUSES.map((item,index)=>{const current=WORKFLOW_STATUSES.indexOf(status);return <div className={index<=current?"reached":""} key={item}><i>{index<current?<Check size={13}/>:index+1}</i><span>{WORKFLOW_LABELS[item]}</span></div>})}</section>
    <div className="business-layout"><div className="business-canvas">
      <section className="business-section creatives-section"><div className="section-heading"><div><span className="technical">Original research</span><h2>Active ad creatives</h2></div></div>{lead.images.length?<div className="original-gallery">{lead.images.map((image,index)=><button type="button" onClick={()=>showImage(image)} key={image.id||index} aria-label={`View creative ${index+1}`}><img src={image.url} alt={image.description||`Ad creative ${index+1}`}/></button>)}</div>:<div className="gallery-empty"><ImageIcon/><strong>No original images</strong><p>The employee completed this lead without an image reference.</p></div>}</section>
      <section className="business-section redesign-section" onPaste={handlePaste}><div className="section-heading"><div><span className="technical">Chalkframe output</span><h2>Redesign</h2></div><button onClick={()=>setRedesigns([...redesigns,{url:"",description:""}])}><Plus size={15}/>Add redesign</button></div><p className="section-intro">Paste a copied image to compress, upload, and save it automatically—or paste an existing image link into an Image URL field.</p><label className="chatgpt-field">ChatGPT URL <span>Optional</span><input type="url" value={chatgptUrl} onChange={event=>setChatgptUrl(event.target.value)} placeholder="https://chatgpt.com/share/..."/></label><div className={`paste-image-zone ${uploading?"uploading":""}`} tabIndex={0} onPaste={handlePaste}><ImageIcon size={21}/><div><strong>{uploading?"Optimizing and uploading…":"Paste a copied image here"}</strong><span>Click this area, then press ⌘V or Ctrl+V · PNG, JPEG, GIF, or WebP up to 4 MB</span></div></div><div className="redesign-editor">{redesigns.map((image,index)=><div className="redesign-card" key={index}>{image.url?<button type="button" className="redesign-preview" onClick={()=>showImage(image)} aria-label={`View redesign ${index+1}`}><img src={image.url} alt={`Redesign ${index+1}`}/></button>:<div className="redesign-placeholder"><ImageIcon size={26}/><span>Preview</span></div>}<div className="redesign-fields"><label>Image URL<input type="url" value={image.url} onChange={e=>setRedesigns(redesigns.map((item,i)=>i===index?{...item,url:e.target.value}:item))} placeholder="Paste an image URL"/></label><label>Description<input value={image.description||""} onChange={e=>setRedesigns(redesigns.map((item,i)=>i===index?{...item,description:e.target.value}:item))} placeholder="What changed in this redesign"/></label></div>{redesigns.length>1&&<button className="remove-redesign" aria-label="Remove redesign" onClick={()=>setRedesigns(redesigns.filter((_,i)=>i!==index))}><X size={14}/></button>}</div>)}</div></section>
    </div><aside className="business-sidebar">
      <section className="fact-card"><span className="technical">Business details</span><h2>Contact record</h2><Fact label="Facebook" value={lead.facebook_url} link/><Fact label="Instagram" value={lead.instagram_url} link/><Fact label="Email" value={lead.email} icon={<Mail size={14}/>} href={lead.email?`mailto:${lead.email}`:undefined}/><Fact label="Phone" value={lead.phone} icon={<Phone size={14}/>} href={lead.phone?`tel:${lead.phone}`:undefined}/><Fact label="Website" value={lead.website_status==="no"?"No website found":lead.website_url||"Not checked"} link={Boolean(lead.website_url)}/><div className="research-notes"><span>Employee notes</span><p>{lead.notes||"No additional information was added."}</p></div><div className="completed-meta"><span>Research owner</span><strong>{lead.completed_by_name||"Not completed"}</strong>{lead.completed_at&&<small>{new Date(lead.completed_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</small>}</div></section>
      <section className="admin-note-card"><div><StickyNote size={17}/><span className="technical">Private admin notes</span></div><p>Only administrators can read these notes.</p><textarea rows={8} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add follow-up context, positioning ideas, or contact outcomes…"/></section>
      {(message||error)&&<div className={`workspace-message ${error?"error":""}`}>{error||message}</div>}<button className="save-workspace" onClick={save} disabled={saving}><Save size={16}/>{saving?"Saving…":"Save workspace"}</button><button className="delete-business" onClick={()=>setConfirmDelete(true)} disabled={saving}><Trash2 size={15}/>Delete business</button>
    </aside></div>{selectedImage&&<div className="image-lightbox" role="dialog" aria-modal="true" aria-label="Creative preview" onMouseDown={event=>{if(event.target===event.currentTarget)setSelectedImage(null)}}><div className="lightbox-card"><button className="lightbox-close" onClick={()=>setSelectedImage(null)} aria-label="Close image preview"><X size={20}/></button><div className="lightbox-art"><img src={selectedImage.url} alt={selectedImage.description||"Creative preview"}/></div><aside><span className="technical">Image description</span><p>{selectedImage.description||"No description was added for this image."}</p><button className="copy-description" onClick={copyDescription} disabled={!selectedImage.description}>{copied?<><Check size={16}/>Copied</>:<><Copy size={16}/>Copy description</>}</button><a href={selectedImage.url} target="_blank" rel="noreferrer">Open original image <ArrowUpRight size={13}/></a></aside></div></div>}{confirmDelete&&<div className="modal-backdrop"><div className="confirm-delete" role="alertdialog" aria-modal="true" aria-labelledby="delete-title"><span><Trash2 size={20}/></span><h2 id="delete-title">Delete this business?</h2><p>“{lead.title||"Meta ad business"}” and all its research and redesign images will be permanently removed.</p><div><button className="secondary-button" onClick={()=>setConfirmDelete(false)} disabled={saving}>Cancel</button><button className="danger-button" onClick={remove} disabled={saving}>{saving?"Deleting…":"Yes, delete business"}</button></div></div></div>}
  </main>
}

function Fact({label,value,link,href,icon}:{label:string;value:string|null;link?:boolean;href?:string;icon?:React.ReactNode}){const target=href||(link&&value?value:undefined);return <div className="fact"><span>{label}</span>{target?<a href={target} target={target.startsWith("http")?"_blank":undefined} rel="noreferrer">{icon}{value}<ArrowUpRight size={11}/></a>:<strong>{value||"Not found"}</strong>}</div>}
