"use client";

import { useMemo, useState } from "react";
import { ArrowUpRight, Check, ChevronDown, Image as ImageIcon, LayoutGrid, Link2, LogOut, Plus, Search, UserPlus, Users, X } from "lucide-react";
import { logoutAction } from "@/app/actions";
import type { SessionUser } from "@/lib/db";

type ImageItem = { id?: string; url: string; description: string };
type Lead = { id: string; ad_url: string; title: string | null; status: "pending" | "completed"; facebook_url: string | null; instagram_url: string | null; email: string | null; phone: string | null; has_website: boolean; website_url: string | null; notes: string | null; images: ImageItem[]; completed_by_name?: string; completed_at?: string };

export default function Dashboard({ initialLeads, initialUsers, user }: { initialLeads: Lead[]; initialUsers: any[]; user: SessionUser }) {
  const [leads, setLeads] = useState(initialLeads); const [users, setUsers] = useState(initialUsers);
  const [tab, setTab] = useState<"all"|"pending"|"completed">("all"); const [search, setSearch] = useState(""); const [modal, setModal] = useState<"lead"|"details"|"user"|null>(null); const [activeLead, setActiveLead] = useState<Lead|null>(null); const [busy, setBusy] = useState(false);
  const completed = leads.filter(l => l.status === "completed").length; const pending = leads.length - completed; const earned = completed * 10; const progress = Math.min(100, earned / 100);
  const filtered = useMemo(() => leads.filter(l => (tab === "all" || l.status === tab) && `${l.title} ${l.ad_url} ${l.email}`.toLowerCase().includes(search.toLowerCase())), [leads, tab, search]);
  async function post(path: string, data: unknown) { setBusy(true); const res = await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const body = await res.json(); setBusy(false); if (!res.ok) throw new Error(body.error || "Request failed"); return body; }
  async function createLead(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const result = await post("/api/leads", { adUrl: f.get("adUrl"), title: f.get("title") }); setLeads([result.lead, ...leads]); setModal(null); }
  async function createUser(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const result = await post("/api/users", { username: f.get("username"), name: f.get("name"), password: f.get("password") }); setUsers([result.user, ...users]); setModal(null); }
  async function saveDetails(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if (!activeLead) return; const f = new FormData(e.currentTarget); const urls = f.getAll("imageUrl").map(String); const descriptions = f.getAll("imageDescription").map(String); const result = await post(`/api/leads/${activeLead.id}/complete`, { facebookUrl:f.get("facebookUrl"), instagramUrl:f.get("instagramUrl"), email:f.get("email"), phone:f.get("phone"), hasWebsite:f.get("hasWebsite") === "on", websiteUrl:f.get("websiteUrl"), notes:f.get("notes"), images:urls.map((url,i)=>({url,description:descriptions[i]})).filter(x=>x.url) }); setLeads(leads.map(l=>l.id===activeLead.id?result.lead:l)); setModal(null); setActiveLead(null); }
  function openDetails(lead: Lead) { setActiveLead(lead); setModal("details"); }
  return <main className="app-shell">
    <aside className="sidebar"><img src="/brand/chalkframe-logo-dark.svg" alt="Chalkframe" className="side-logo"/><nav><button className="nav-item active"><LayoutGrid size={18}/>Leads</button>{user.role === "admin" && <button className="nav-item" onClick={()=>document.getElementById("team")?.scrollIntoView()}><Users size={18}/>Team</button>}</nav><div className="side-bottom"><div className="user-chip"><span>{user.name.charAt(0)}</span><div><strong>{user.name}</strong><small>{user.role}</small></div></div><form action={logoutAction}><button className="logout" aria-label="Sign out"><LogOut size={17}/></button></form></div></aside>
    <section className="workspace"><header className="topbar"><div><span className="technical">Chalkframe / Leads</span><h1>Lead workspace</h1></div><div className="header-actions">{user.role === "admin" && <button className="secondary-button" onClick={()=>setModal("user")}><UserPlus size={17}/>Add employee</button>}{user.role === "admin" && <button className="primary-button compact" onClick={()=>setModal("lead")}><Plus size={17}/>Add ad link</button>}</div></header>
      <section className="scoreboard"><div className="score-main"><span className="technical">Earnings progress</span><div className="amount-row"><strong>₹{earned.toLocaleString("en-IN")}</strong><span>of ₹10,000 goal</span></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div><small>₹10 earned for every completed lead</small></div><div className="stat"><span>Completed</span><strong>{completed}</strong><small><i className="dot done"/>Research added</small></div><div className="stat"><span>Pending</span><strong>{pending}</strong><small><i className="dot"/>Ready to work</small></div></section>
      <section className="queue"><div className="queue-head"><div><span className="technical">Research queue</span><h2>Ad leads</h2></div><div className="filters"><label className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search leads"/></label><div className="tabs">{(["all","pending","completed"] as const).map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div></div></div>
        <div className="lead-table"><div className="lead-row lead-labels"><span>Ad source</span><span>Status</span><span>Research</span><span>Action</span></div>{filtered.length===0?<div className="empty"><Link2/><h3>No leads here yet</h3><p>{user.role==="admin"?"Add a Meta Ad Library link to start the queue.":"Your administrator will add links to this queue."}</p></div>:filtered.map((lead,i)=><div className="lead-row" key={lead.id}><div className="ad-cell"><span className="row-index">{String(i+1).padStart(2,"0")}</span><div><strong>{lead.title || "Meta ad"}</strong><a href={lead.ad_url} target="_blank" rel="noreferrer">Open ad in Meta Library <ArrowUpRight size={13}/></a></div></div><span className={`status ${lead.status}`}><i/>{lead.status}</span><div className="research-cell">{lead.images?.length?<><div className="thumb-stack">{lead.images.slice(0,3).map((im,j)=><img key={j} src={im.url} alt="Ad creative"/>)}</div><span>{lead.images.length} image{lead.images.length!==1?"s":""}</span></>:<span className="muted">Not added</span>}</div><button className={lead.status==="completed"?"view-button":"detail-button"} onClick={()=>openDetails(lead)}>{lead.status==="completed"?"View details":"Add details"}<ChevronDown size={15}/></button></div>)}</div>
      </section>
      {user.role==="admin" && <section id="team" className="team-section"><div><span className="technical">Access control</span><h2>Team members</h2></div><div className="team-grid">{users.map(u=><div className="team-card" key={u.id}><span>{u.name.charAt(0)}</span><div><strong>{u.name}</strong><small>@{u.username} · {u.role}</small></div><i className={u.active?"online":""}/></div>)}</div></section>}
    </section>
    {modal && <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className={`modal ${modal==="details"?"wide":""}`}><button className="modal-close" onClick={()=>setModal(null)}><X size={18}/></button>{modal==="lead"&&<SimpleModal eyebrow="New queue item" title="Add an ad link"><form onSubmit={createLead}><Field label="Label (optional)" name="title" placeholder="e.g. Dental clinic — Hyderabad"/><Field label="Meta Ad Library URL" name="adUrl" type="url" required placeholder="https://www.facebook.com/ads/library/..."/><button disabled={busy} className="primary-button">{busy?"Adding…":"Add to queue"}<Plus size={17}/></button></form></SimpleModal>}{modal==="user"&&<SimpleModal eyebrow="Access control" title="Add employee"><form onSubmit={createUser}><Field label="Full name" name="name" required/><Field label="Username" name="username" required/><Field label="Temporary password" name="password" type="password" required minLength={8}/><button disabled={busy} className="primary-button">{busy?"Creating…":"Create employee"}<UserPlus size={17}/></button></form></SimpleModal>}{modal==="details"&&activeLead&&<DetailsForm lead={activeLead} onSubmit={saveDetails} busy={busy} readonly={activeLead.status==="completed"}/>}</div></div>}
  </main>;
}

function SimpleModal({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <><span className="technical">{eyebrow}</span><h2>{title}</h2>{children}</>}
function Field(props: React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...rest}=props;return <label>{label}<input {...rest}/></label>}
function DetailsForm({lead,onSubmit,busy,readonly}:{lead:Lead;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;busy:boolean;readonly:boolean}) { const [images,setImages]=useState<ImageItem[]>(lead.images?.length?lead.images:[{url:"",description:""}]); const [hasWebsite,setHasWebsite]=useState(lead.has_website); return <><span className="technical">{readonly?"Completed lead":"Complete research"}</span><h2>{lead.title||"Meta ad details"}</h2><a className="source-link" href={lead.ad_url} target="_blank" rel="noreferrer">View source ad <ArrowUpRight size={14}/></a><form onSubmit={onSubmit}><div className="form-grid"><Field label="Facebook page" name="facebookUrl" type="url" defaultValue={lead.facebook_url||""}/><Field label="Instagram profile" name="instagramUrl" type="url" defaultValue={lead.instagram_url||""}/><Field label="Email" name="email" type="email" defaultValue={lead.email||""}/><Field label="Contact number" name="phone" type="tel" defaultValue={lead.phone||""}/></div><label className="check"><input type="checkbox" name="hasWebsite" checked={hasWebsite} onChange={e=>setHasWebsite(e.target.checked)}/><span><Check size={13}/></span>They have a website</label>{hasWebsite&&<Field label="Website URL" name="websiteUrl" type="url" required defaultValue={lead.website_url||""}/>}<label>Other information<textarea name="notes" rows={3} defaultValue={lead.notes||""} placeholder="Add useful context, decision-maker details, or observations"/></label><div className="image-section"><div className="image-title"><div><span className="technical">Creative references</span><h3>Image URLs</h3></div>{!readonly&&<button type="button" className="text-button" onClick={()=>setImages([...images,{url:"",description:""}])}><Plus size={15}/>Add image</button>}</div>{images.map((im,i)=><div className="image-entry" key={i}>{im.url?<img src={im.url} alt="Preview"/>:<div className="image-placeholder"><ImageIcon size={22}/></div>}<div><Field label={`Image ${i+1} URL`} name="imageUrl" type="url" value={im.url} onChange={e=>setImages(images.map((x,j)=>j===i?{...x,url:e.target.value}:x))}/><Field label="Description" name="imageDescription" value={im.description||""} onChange={e=>setImages(images.map((x,j)=>j===i?{...x,description:e.target.value}:x))} placeholder="What this creative shows"/></div>{!readonly&&images.length>1&&<button type="button" className="remove-image" onClick={()=>setImages(images.filter((_,j)=>j!==i))}><X size={15}/></button>}</div>)}</div>{!readonly&&<button disabled={busy} className="primary-button save-details">{busy?"Saving…":"Save and mark complete"}<Check size={17}/></button>}</form></> }
